import Foundation
import SQLiteData

/// The high-level route from goal to mastery. Owns `Stage`s; each stage owns
/// `Sprint`s; each sprint owns `Session`s. Per `ARCHITECTURE.md §3`,
/// `PlanningEngine` produces this from a `LearningGoal` and only fully
/// expands the near-term stages — far stages stay as titles + intent until
/// the learner approaches them.
@Table
public struct ProgramBlueprint: Identifiable, Equatable, Sendable {
    public let id: UUID
    public var goalID: LearningGoal.ID
    /// One-paragraph framing surfaced on the Home Dashboard hero card.
    /// Generated by the planner so the user sees the plan's intent
    /// before drilling into stages.
    public var summary: String = ""
    /// Planner's estimate of total program duration, in weeks. Nullable
    /// because for some goals "until you can do X" matters more than
    /// fixed weeks; nil means the dashboard hides the duration chip.
    public var durationWeeks: Int?
    public var createdAt: Date = Date()
    public var updatedAt: Date = Date()
}
