import Foundation
import SQLiteData

/// A scheduled spaced-repetition item. Generated by `AdaptationEngine`
/// from `MasteryState` updates and surfaced on the Review Vault screen
/// when due. `intervalDays` follows the SM-2-style cadence after each
/// successful review; lapses reset the interval and increment
/// `lapseCount` so chronically weak concepts surface for a recovery
/// session rather than another flashcard.
@Table
public struct ReviewItem: Identifiable, Equatable, Sendable {
    public let id: UUID
    public var conceptID: ConceptNode.ID
    public var dueAt: Date = Date()
    public var intervalDays: Int = 1
    public var lapseCount: Int = 0
    public var createdAt: Date = Date()
}
